# Site settings
title: bronzehedwick
email: bronzehedwick@gmail.com
author: Chris DeLuca
description: "Writer, Comedian, Developer."
baseurl: ""
url: "http://bronzehedwick.github.io"
google_analytics: "UA-54335228-1"
twitter: "https://twitter.com/chrisjohndeluca"
github: "https://github.com/bronzehedwick"
youtube: "https://www.youtube.com/channel/UChfcp3RhN0FJOnTZquDRzYw"
stackoverflow: "http://stackoverflow.com/users/1143575/bronzehedwick"
drupal: "https://www.drupal.org/u/bronzehedwick"
linkedin: "https://www.linkedin.com/in/christopherdeluca"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
