# Site settings
title: bronzehedwick
email: bronzehedwick@gmail.com
author: Chris DeLuca
description: "Writer, Comedian, Developer."
baseurl: ""
url: "http://bronzehedwick.github.io"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
